package jp.ac.keio.bio.fun.xitosbml.util;

import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.xml.stream.XMLStreamException;

import org.sbml.jsbml.Model;
import org.sbml.jsbml.SBMLDocument;
import org.sbml.jsbml.SBMLException;
import org.sbml.jsbml.SBMLWriter;
import org.sbml.jsbml.TidySBMLWriter;

import ij.IJ;
import ij.io.SaveDialog;

/**
 * The class ModelSaver, which is an utility class to save SBML document to a file.
 * The saved SBML file will contain an annotation generated by this class.
 * The annotation contains following information:
 * <ul>
 *     <li>Model ID</li>
 *     <li>Hostname</li>
 *     <li>Date</li>
 *     <li>XitoSBML version and credit</li>
 * </ul>
 * Date Created: Oct 3, 2015
 *
 * @author Kaito Ii &lt;ii@fun.bio.keio.ac.jp&gt;
 * @author Akira Funahashi &lt;funa@bio.keio.ac.jp&gt;
 */
public class ModelSaver {
	
	/** The SBML document. */
	private SBMLDocument document;
	
	/** The SBML model. */
	private Model model;
	
	/** The path to the directory where SBML file is located. */
	private String path;
	
	/** The filename of the SBML file. */
	private String name;
	
	/**
	 * Instantiates a new model saver.
	 *
	 * @param document the SBML document
	 */
	public ModelSaver(SBMLDocument document){
		this.document = document;
		this.model = document.getModel();
	}
	
	/**
	 * Save an SBML document to a file.
	 * The SBML document is written to the file by org.sbml.jsbml.TidySBMLWriter().
	 * The filename and path of the directory will be specified by the user through SaveDialog.
	 */
	public void save(){
		SaveDialog sd = new SaveDialog("Save SBML Document", model.getId(), ".xml");
	
		path = sd.getDirectory();
		name = sd.getFileName();
			
		IJ.log("filename = " + name);
		
		setAnnotation();
		
		try {		
			if(name.contains(".xml"))	
				name = name.substring(0, name.indexOf('.'));
			document.getModel().setId(name);
			SBMLWriter.write(document, new File(path + "/" + name + ".xml"), ' ', (short) 2); 
		} catch(NullPointerException e) {
			System.out.println("SBML document was not saved");
		} catch (SBMLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (XMLStreamException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	

		try {
			String docStr = new TidySBMLWriter().writeSBMLToString(document);
	        IJ.log(docStr);
		} catch (SBMLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (XMLStreamException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 

	}

	/**
	 * Sets the annotation to the model.
	 * The annotation will be generated by the following information:
	 * <ul>
	 *     <li>Model ID</li>
	 *     <li>Hostname</li>
	 *     <li>Date</li>
	 *     <li>XitoSBML version and credit</li>
	 * </ul>
	 */
	private void setAnnotation(){
		String id = "";
		try {
			id = InetAddress.getLocalHost().getHostName();
		} catch (UnknownHostException e) {
			System.out.println("Unknown host");
		}
		IJ.log("hostname = " + id);
		
		String annot = "This " + model.getId() + " model is created";
		
		if(!id.equals("")) {
		  if (id.contains(".")) {
		    id = id.substring(0,  id.indexOf("."));
		  }
			annot = annot.concat(" by " + id);
		}
			
		Calendar date = new GregorianCalendar();
		annot = annot.concat(" in " + date.getTime());
		

		try {
			document.setNotes(annot);
			model.setNotes("This model has been built using XitoSBML-" + this.getClass().getPackage().getImplementationVersion() + " implemented by Kaito Ii and Akira Funahashi "
					+ "from Funahashi Lab. Keio University, Japan with substantial contributions from Kota Mashimo, Mitsunori Ozeki, and Noriko Hiroi");
		} catch (XMLStreamException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Gets the path to the directory where SBML file is located.
	 *
	 * @return the path to the directory where SBML file is located.
	 */
	public String getPath() {
		return path;
	}

	/**
	 * Gets the filename of the SBML file.
	 *
	 * @return the filename of the SBML file
	 */
	public String getName() {
		return name;
	}

}
